### ISSUE TITLE
Relevant code not found

### ISSUE THREAD

**Issue by JJplane** [ckarouzos/slp_daptmlm#1]
excellent work！Looking forward to uploading the relevant code about the paper “Unsupervised Domain Adaptation through Language Modeling”.

**Comment by ckarouzos** [comment]
Please check here: https://github.com/ckarouzos/slp_daptmlm/blob/master/amazon/bertprepar.py
Apologies for any access issues.

**Comment by suvaansh** [comment]
Does this link provide code for the paper “Unsupervised Domain Adaptation through Language Modeling”?
If yes, please add some clarifications on how to use in ReadMe. Thanks!
